### ISSUE TITLE
Guestbook

### ISSUE THREAD

**Issue by y0geshx** [y0geshx/vibrantfix#1]
Hello :)
Sign my guestbook by leaving a comment here!

![guestbook](https://raw.githubusercontent.com/vibrantfix/vibrantfix/main/assets/gif/guestbook.gif)

**Comment by vibrantfix** [comment]
Does this guestbook work now?

**Comment by vibrantfix** [comment]
Does this guestbook work now??

**Comment by vibrantfix** [comment]
Does this guestbook work now??!

**Comment by vibrantfix** [comment]
yes it's working :smile:
